Repository nekomeowww/insights-bot, pull requests merged in 2023-05, with the labels that each got.

#39 feat: add installation support for other workspaces
  README.md
  docker-compose.yml
  ent/client.go
  ent/ent.go
  ent/hook/hook.go
  ent/internal/schemaconfig.go
  ent/migrate/schema.go
  ent/mutation.go
  ent/predicate/predicate.go
  ent/runtime.go
  ent/schema/slackoauthcredentials.go
  ent/slackoauthcredentials.go
  ent/slackoauthcredentials/slackoauthcredentials.go
  ent/slackoauthcredentials/where.go
  ent/slackoauthcredentials_create.go
  ent/slackoauthcredentials_delete.go
  ent/slackoauthcredentials_query.go
  ent/slackoauthcredentials_update.go
  ent/tx.go
  internal/bots/slack/handlers.go
  internal/bots/slack/processors.go
  internal/bots/slack/services.go
  internal/bots/slack/services_test.go
  internal/bots/slack/slack.go
  internal/bots/slack/types.go
  internal/configs/configs.go
Labels: enhancement

#62 fix(slack): handle token expired error when send message
  ent/migrate/schema.go
  ent/mutation.go
  ent/runtime.go
  ent/schema/slackoauthcredentials.go
  ent/slackoauthcredentials.go
  ent/slackoauthcredentials/slackoauthcredentials.go
  ent/slackoauthcredentials/where.go
  ent/slackoauthcredentials_create.go
  ent/slackoauthcredentials_update.go
  internal/bots/slack/handlers.go
  internal/bots/slack/processors.go
  internal/bots/slack/services.go
  internal/bots/slack/services_test.go
  internal/bots/slack/types.go
  pkg/bots/slackbot/slackbot.go
  pkg/bots/slackbot/slackbot_test.go
  pkg/tutils/slack.go
Labels: bug

#65 fix(slack): handle token expired error when send message
  ent/migrate/schema.go
  ent/mutation.go
  ent/runtime.go
  ent/schema/slackoauthcredentials.go
  ent/slackoauthcredentials.go
  ent/slackoauthcredentials/slackoauthcredentials.go
  ent/slackoauthcredentials/where.go
  ent/slackoauthcredentials_create.go
  ent/slackoauthcredentials_update.go
  internal/bots/slack/handlers.go
  internal/bots/slack/processors.go
  internal/bots/slack/services.go
  internal/bots/slack/services_test.go
  internal/bots/slack/types.go
  pkg/bots/slackbot/slackbot.go
  pkg/bots/slackbot/slackbot_test.go
  pkg/tutils/slack.go
Labels: bug

#72 chore: add slack installation icon to readme
  README.md
  internal/bots/telegram/handlers/recap/toggle_recap.go
Labels: documentation

#91 feat: add discord integration for /smr command
  .env.example
  .gitignore
  README.md
  cmd/insights-bot/main.go
  docker-compose.yml
  go.mod
  go.sum
  internal/bots/discord/commanddef.go
  internal/bots/discord/discord.go
  internal/bots/discord/listeners.go
  internal/bots/slack/handlers.go
  internal/bots/slack/types.go
  internal/configs/configs.go
  internal/models/smr/smr.go
  internal/services/health/health.go
Labels: enhancement

#94 fix: discord ran not ignored when discord not initialized
  internal/bots/discord/discord.go
Labels: bug

#99 chore: introduce rueidis and timecapsule for cron job queues
  .env.example
  README.md
  docker-compose.yml
  go.mod
  go.sum
  internal/bots/telegram/handlers/recap/toggle_recap.go
  internal/configs/configs.go
  internal/datastore/datastore.go
  internal/datastore/rueidis.go
  internal/datastore/timecapsule.go
  internal/models/chathistories/chat_histories.go
  internal/models/tgchats/feature_flags.go
  internal/models/tgchats/tgchat.go
  internal/services/autorecap/autorecap.go
  internal/services/health/health.go
  internal/services/services.go
  pkg/types/redis/keys.go
  pkg/types/timecapsules/auto_recap.go
Labels: bug, enhancement
